Fix covereage error

diff --git a/scripts/coverage b/scripts/coverage
--- a/scripts/coverage
+++ b/scripts/coverage
@@ -25,18 +25,18 @@ show_cover_report() {
 
 push_to_coveralls() {
     echo "Pushing coverage statistics to coveralls.io"
-    goveralls -coverprofile="$profile"
+    goveralls -coverprofile="$profile" -service=travis-ci
 }
 
 generate_cover_data $(go list ./...)
 show_cover_report func
 case "$1" in
-"")
-    ;;
---html)
-    show_cover_report html ;;
---coveralls)
-    push_to_coveralls ;;
-*)
-    echo >&2 "error: invalid option: $1"; exit 1 ;;
-Esac
+    "")
+        ;;
+    --html)
+        show_cover_report html ;;
+    --coveralls)
+        push_to_coveralls ;;
+    *)
+        echo >&2 "error: invalid option: $1"; exit 1 ;;
+esac
